services:
  postgres:
    image: postgres:15-alpine
    container_name: airflow-postgres
    networks:
      - airflow-net
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      timeout: 5s
      retries: 10

  airflow:
    build: .
    container_name: airflow
    user: "${AIRFLOW_UID:-50000}:0"
    networks:
      - airflow-net
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ../dbt:/opt/airflow/dbt
      - ./logs:/opt/airflow/logs
      - "${LOCAL_GCS_JSON_CREDENTIALS_PATH}:${CONTAINER_JSON_CREDENTIALS_PATH}"
    ports:
      - "8080:8080"
    command: bash -c "
      cd $DBT_PROJECT_PATH &&
      $DBT_VIRTUAL_ENVIRONMENT_PATH deps &&
      $DBT_VIRTUAL_ENVIRONMENT_PATH parse &&
      airflow standalone
      "

volumes:
  postgres_data:

networks:
  airflow-net:
    driver: bridge